name: Run tests

on:
  push

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      METMUSEUM_URL: https://collectionapi.metmuseum.org/public/collection/v1
      HTTPBIN_URL: https://httpbin.org

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Create venv
        run: uv venv
      - name: Sync dependencies
        run: uv sync --extra dev --frozen
      - name: Run tests
        run: uv run pytest